name: Generate Terraform Docs for All Modules

on:
  push:
    paths:
      - '**/*.tf'
      - '**/README.md'
  pull_request:
    paths:
      - '**/*.tf'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install terraform-docs
        run: |
          curl -sSLo terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.17.0/terraform-docs-v0.17.0-linux-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          sudo mv terraform-docs /usr/local/bin/

      - name: Generate docs in each module folder
        shell: bash
        run: |
          for dir in $(find . -mindepth 2 -maxdepth 2 -type f -name "main.tf" -exec dirname {} \;); do
            echo "📄 Generating docs in $dir"
            terraform-docs markdown table "$dir" \
              --output-file README.md \
              --output-mode inject
          done


      - name: Commit updated docs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(terraform): auto-generate module documentation"
          commit_user_name: terraform-docs[bot]
          commit_user_email: terraform-docs@users.noreply.github.com
