name: Generate Terraform Docs

on:
  push:
    paths:
      - '**/*.tf'
      - '**/README.md'
  pull_request:
    paths:
      - '**/*.tf'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup terraform-docs
        uses: terraform-docs/gh-actions@v1.1.0
        with:
          output-file: README.md
          output-method: inject
          git-push: false

      - name: Generate docs in each module folder
        shell: bash
        run: |
          for dir in $(find . -type f -name "main.tf" -exec dirname {} \;); do
            echo "📄 Generating docs in $dir"
            terraform-docs markdown table "$dir" \
              --output-file README.md \
              --output-mode inject
          done

      - name: Commit updated docs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(terraform): auto-generate module documentation"
          commit_user_name: terraform-docs[bot]
          commit_user_email: terraform-docs@users.noreply.github.com
